// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Swoosh.Api.Data;

#nullable disable

namespace Swoosh.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405000816_AddRecurringTaskFields")]
    partial class AddRecurringTaskFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Swoosh.Api.Domain.NoteCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPositionX")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPositionY")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NoteCards");
                });

            modelBuilder.Entity("Swoosh.Api.Domain.RecurringTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedIcon")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedIsActive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPinned")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRating")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRecurrenceInterval")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRecurrenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RecurringTasks");
                });

            modelBuilder.Entity("Swoosh.Api.Domain.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedIsCompleted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRemindAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Swoosh.Api.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedCompletedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedDeadline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedIcon")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPinned")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRating")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTimerDuration")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Swoosh.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptionSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
